ProtoXEP: Bookmark Pinning
xsf/xeps pull request #1182
Opened 2022-06-04 11:04 UTC by edhelas

This extention allow users to pin XEP-0402 Bookmarks

Re-submitting from a custom branch

2022-06-14 18:56 UTC, horazont requested changes

2022-06-14 18:56 UTC, horazont commented on inbox/bookmark-pinning.xml
> +  <status>Draft</status>
This must be `<status>ProtoXEP</status>`.

2022-06-14 18:56 UTC, horazont commented on inbox/bookmark-pinning.xml
> +  <number>xxx</number>
This must be `<number>xxxx</number>` for ProtoXEPs.

2022-07-05 20:07 UTC, edhelas commented
Hi @horazont I made the changes. Is everything is fine for you :) ?

2022-07-13 15:02 UTC, merged