XEP-0198: Add section defining SASL2 and BIND2 interaction
xsf/xeps pull request #1215
Opened 2022-10-06 20:56 UTC by tmolitor-stud-tu

The title says it all: I've added a section specifying interaction with the upcoming versions of the SASL2 (XEP-0388) and BIND2 (XEP-0386) XEPs.

See #1214 for details about the SASL2 changes.

2022-10-12 16:05 UTC, horazont commented
Even though this is pending the acceptance of #1214, I'm still submitting this to council to judge the general approach of having this in '198 as well as any concerns which may exist under the precondition of #1214 being merged.

2022-10-12 21:08 UTC, tmolitor-stud-tu commented
For reference, here is the rendered version: https://dyn.eightysoft.de/final/xep-0198.html#inline

2023-04-19 09:30 UTC, mar-v-in requested changes

2023-04-19 09:30 UTC, mar-v-in commented on xep-0198.xml
> +    <p>To indicate support for inlining the activation of Stream Management into the resource binding process, the server adds a &lt;feature/> element in the namespace "urn:xmpp:sm:3" into the &lt;in
should be `server adds a &lt;feature/> element with var attribute set to "urn:xmpp:sm:3" in the &lt;inline/> element`

2023-09-06 17:07 UTC, iNPUTmice commented
Hi @tmolitor-stud-tu the feedback @mar-v-in provided hasn’t been addressed yet. This is why council has rejected this for now. But once this minor thing is fixed I can put it back on the agenda.

2023-09-08 00:39 UTC, tmolitor-stud-tu commented
@iNPUTmice I'm sorry, I somehow missed that feedback. Should be addressed now :)

2023-09-11 08:52 UTC, iNPUTmice commented on xep-0198.xml
> +    <p>To indicate support for inlining stream resumption into the authentication process, the server adds a &lt;resume/> element in the namespace "urn:xmpp:sm:3" to the &lt;inline/> element of SASL2
The example uses a `<sm/>` element and so do Conversations and prosody

2024-03-11 06:24 UTC, iNPUTmice commented
Merged as #1294

2024-03-11 06:24 UTC, closed without merging